language: php

php:
  - "7.1"
  - "7.2"
  - "nightly"

env:
  - CONTAO_VERSION=contao/core-bundle ~4.4.0
  - CONTAO_VERSION=contao/core-bundle ~4.5.0

matrix:
  exclude:

sudo: false

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer require $CONTAO_VERSION --no-update
  - travis_retry composer update --prefer-dist --no-interaction

script: ant -keep-going

allow_failure:
  - php: "nightly"

# Hack to make things work again - we can not use a shallow repository.
git:
  depth: 2147483647

cache:
  directories:
    - vendor
